#!/bin/bash

# read -p "Do you want to install the following dependencies ? (y/n): " answer
# if [ "$answer" != "${answer#[Yy]}" ]; then
pip install numpy tensorflow==2.14 dearpygui==1.10.0 opencv-python matplotlib
# else
    # echo "Aborted"
# fi
