#!/bin/bash

# read -p "Do you want to install the following dependencies ? (y/n): " answer
# if [ "$answer" != "${answer#[Yy]}" ]; then
pip install numpy tensorflow dearpygui opencv-python matplotlib
# else
    # echo "Aborted"
# fi
