#!/bin/bash

read -p "Do you want to install dependencies? (y/n): " answer
if [ "$answer" != "${answer#[Yy]}" ]; then
    # Installer les dépendances
    pip install numpy tensorflow dearpygui
else
    echo "Installation des dépendances annulée."
fi
